### ISSUE TITLE
Instances for MonadThrow and MonadCatch typeclasses

### ISSUE THREAD

**Issue by starper** [cjdev/test-fixture#31]
From [exceptions](https://hackage.haskell.org/package/exceptions-0.8.3) package

**Comment by jxv** [comment]
@starper `test-fixture` won't support this out of the box. You'll have to write any related instances yourself. It's not _that_ opinionated. Otherwise, you have two options.
1. [`monad-mock`](https://github.com/cjdev/monad-mock), a latteral improvement over `test-fixture`. Alexis wrote an [example](https://github.com/lexi-lambda/mtl-style-example) how to use it.
2. [`fixie`](https://github.com/jxv/fixie), a fork with an incrementally different opinion using `ExceptT` underneath the testing monad transformer. Currently, it has a `MonadError` instance, but `MonadThrow`/`MonadCatch` could be easily added.

**Comment by lexi-lambda** [comment]
@jxv, I think that @starper is simply talking about lifting instances for `MonadThrow` and `MonadCatch` on `TestFixtureT`, which are quite reasonable, and ought to be added.

**Comment by jxv** [comment]
@starper , do you have an example use case? It could be really that simple as she mentioned.

**Comment by starper** [comment]
@jxv @lexi-lambda yes, i'm talking about instances for `TestFixtureT` like the one for `MonadError` in this [issue](https://github.com/cjdev/test-fixture/issues/20). BTW, do you recommed to use `monad-mock` instead of `test-fixture`?

**Comment by lexi-lambda** [comment]
> do you recommed to use `monad-mock` instead of `test-fixture`?

That’s largely up to you. They have slightly different philosophies. We’ve mostly stopped using `test-fixture` and have switched to `monad-mock` + hand-written fake implementations instead, but `test-fixture` is not inherently bad, it’s just a different style of testing. You might also be interested in my [mtl-style-example](https://github.com/lexi-lambda/mtl-style-example) repo, which tests some mtl-style Haskell code without any mocking at all (which is really the ideal if you can help it).

**Comment by starper** [comment]
@lexi-lambda Thanks
